version: '3'
services:
  web:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - "db"
    environment:
      database_client: mysql
      database__connection__database: web
      database__connection__host: db
      database__connection__user: root
      database__connection__password: root123
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - db-mysql:/var/lib/mysql
    networks:
      - my-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-network
volumes:
  db-mysql:

networks:
  my-network: